services:
  # BACKEND API Service (Chạy trực tiếp bằng Docker)
  api:
    build: .
    container_name: eventhub-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: jdbc:postgresql://postgres:5432/eventdb
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET:-dev-secret-key-minimum-32-characters-long}
      JWT_ACCESS_EXPIRY: 900
      JWT_REFRESH_EXPIRY: 604800
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      EMAIL_FROM: ${EMAIL_FROM}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      QR_SECRET: ${QR_SECRET:-qr-secret-key-for-signing}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    networks:
      - eventhub-net

  # Cổng DB Postgres
  postgres:
    image: postgres:16-alpine
    container_name: eventhub-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eventdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d eventdb" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - eventhub-net

  # Cổng Redis
  redis:
    image: redis:7-alpine
    container_name: eventhub-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redisdata:/data
    networks:
      - eventhub-net

  # Cổng Quản lý DB
  pgadmin:
    image: dpage/pgadmin4
    container_name: eventhub-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - eventhub-net

  # ngrok trong Docker trỏ trực tiếp về service api của Docker
  ngrok:
    image: ngrok/ngrok:latest
    container_name: eventhub-ngrok
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=lash-capsule-cedar.ngrok-free.dev"
      - "api:8080" # Trỏ về container api chạy trong Docker
    depends_on:
      - api
    networks:
      - eventhub-net

volumes:
  pgdata:
  redisdata:

networks:
  eventhub-net:
    driver: bridge
