ALTER TABLE events ADD COLUMN is_approved BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE events ADD COLUMN is_pending_approval BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE events SET is_approved = true WHERE status IN ('PUBLISHED', 'ON_SALE', 'SOLD_OUT', 'ONGOING', 'COMPLETED');
